baseURL = "https://ymiles.com/"
languageCode = "en-us"
title = "YMiles"
theme = "ananke"
publishDir = "public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  site_logo = ""
  description = "Reward your ride. Track, save, and earn with YMiles."
  show_reading_time = true
  mainSections = ["posts"]
  custom_css = ["css/custom.css"]
  favicon = "favicon.ico"
[menu]

  [[menu.main]]
    name = "1099-K"
    url = "/1099-k/"
    weight = 1

  [[menu.main]]
    name = "1099-NEC"
    url = "/1099-nec/"
    weight = 2

  [[menu.main]]
    name = "Deductions"
    url = "/deductions-checklist/"
    weight = 3

  [[menu.main]]
    name = "Schedule C"
    url = "/schedule-c/"
    weight = 4

  [[menu.main]]
    name = "Pricing"
    url = "/training/"
    weight = 5
